version: "2.1"
services:
  syncthing:
    image: lscr.io/linuxserver/syncthing
    container_name: syncthing
    hostname: syncthing #optional
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/London
    volumes:
      
      - /srv/dev-disk-by-uuid-b370b391-24a6-4f18-b38b-1616c5b2ccf8:/home/piragenth/syncthing

    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped
