
---
# Homepage configuration
# See https://fontawesome.com/icons for icons options

title: "Home-Server Dashboard"
subtitle: "home-server"
logo: "assets/icons/server.png"
# icon: "fas fa-skull-crossbones" # Optional icon

header: true
#footer: '<p>Created with <span class="has-text-danger">❤️</span> with <a href="https://bulma.io/">bulma</a>, <a href="https://vuejs.org/">vuejs</a> & <a href="https://fontawesome.com/">font awesome</a> // Fork me on <a href="https://github.com/bastienwirtz/homer"><i class="fab fa-github-alt"></i></a></p>' # set false if you want to hide it.

# Optional theme customization
theme: default
colors:
  light:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#ffffff"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link: "#3273dc"
    link-hover: "#363636"
  dark:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link: "#3273dc"
    link-hover: "#ffdd57"

# Optional message
#message:
  #url: https://b4bz.io
#  style: "is-dark" # See https://bulma.io/documentation/components/message/#colors for styling options.
#  title: "Demo !"
#  icon: "fa fa-grin"
#  content: "This is a dummy homepage demo. <br /> Find more information on <a href='https://github.com/bastienwirtz/homer'>github.com/bastienwirtz/homer</a>"

# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
links:
  - name: "Contribute"
    icon: "fab fa-github"
    url: "https://github.com/bastienwirtz/homer"
    target: "_blank" # optional html a tag target attribute
  - name: "Wiki"
    icon: "fas fa-book"
    url: "https://www.wikipedia.org/"
  # this will link to a second homer page that will load config from additionnal-page.yml and keep default config values as in config.yml file
  # see url field and assets/additionnal-page.yml.dist used in this example:
  - name: "another page!"
    icon: "fas fa-file-alt"
    url: "#additionnal-page" 

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "enp2s0"
    icon: "fas fa-network-wired"
    items:
      - name: "PiHole"
        logo: "assets/tools/pihole.png"
        subtitle: "Ads Blocker"
        tag: "enp2s0"
        url: "http://192.168.1.2:8081/admin"
        target: "_blank" # optional html a tag target attribute

      - name: "NetData"
        logo: "assets/tools/netdata.png"
        subtitle: "Server monitor"
        tag: "enp2s0"
        url: "http://192.168.1.2:19999"
        target: "_blank" # optional html a tag target attribute

      - name: "Guacamole"
        logo: "assets/tools/guacamole.png"
        subtitle: "Remove viewer"
        tag: "enp2s0"
        url: "http://192.168.1.2:8080"
        target: "_blank" # optional html a tag target attribute

      - name: "Yacht"
        logo: "assets/tools/yacht.png"
        subtitle: "Docker manager yacht"
        tag: "enp2s0"
        url: "http://192.168.1.2:8001"
        target: "_blank" # optional html a tag target attribute

      - name: "Portainer"
        logo: "assets/tools/portainer.png"
        subtitle: "Docker manager Portainer"
        tag: "enp2s0"
        url: "http://192.168.1.2:9000"
        target: "_blank" # optional html a tag target attribute

      - name: "Cockpit"
        logo: "assets/tools/cockpit.svg"
        subtitle: "Virtual Machine"
        tag: "enp2s0"
        url: "https://192.168.1.2:9090"
        target: "_blank" # optional html a tag target attribute

      - name: "OpenMediaVault"
        logo: "assets/tools/omv.png"
        subtitle: "NAS"
        tag: "enp2s0"
        url: "http://192.168.1.2:8082"
        target: "_blank" # optional html a tag target attribute

   
  - name: "wlx7cc2c611779b"
    icon: "fas fa-wifi"
    items:
      - name: "PiHole"
        logo: "assets/tools/pihole.png"
        subtitle: "Ads Blocker"
        tag: "wlx7cc2c611779b"
        url: "http://192.168.12.166:8081/admin"
        target: "_blank" # optional html a tag target attribute

      - name: "NetData"
        logo: "assets/tools/netdata.png"
        subtitle: "Server monitor"
        tag: "wlx7cc2c611779b"
        url: "http://192.168.12.166:19999"
        target: "_blank" # optional html a tag target attribute

      - name: "Guacamole"
        logo: "assets/tools/guacamole.png"
        subtitle: "Remove viewer"
        tag: "wlx7cc2c611779b"
        url: "http://192.168.12.166:8080"
        target: "_blank" # optional html a tag target attribute

      - name: "Yacht"
        logo: "assets/tools/yacht.png"
        subtitle: "Docker manager yacht"
        tag: "wlx7cc2c611779b"
        url: "http://192.168.12.166:8001"
        target: "_blank" # optional html a tag target attribute

      - name: "Portainer"
        logo: "assets/tools/portainer.png"
        subtitle: "Docker manager Portainer"
        tag: "wlx7cc2c611779b"
        url: "http://192.168.12.166:9000"
        target: "_blank" # optional html a tag target attribute

      - name: "Cockpit"
        logo: "assets/tools/cockpit.svg"
        subtitle: "Virtual Machine"
        tag: "wlx7cc2c611779b"
        url: "https://192.168.12.166:9090"
        target: "_blank" # optional html a tag target attribute

      - name: "OpenMediaVault"
        logo: "assets/tools/omv.png"
        subtitle: "NAS"
        tag: "wlx7cc2c611779b"
        url: "http://192.168.12.166:8082"
        target: "_blank" # optional html a tag target attribute
